### ISSUE TITLE
Overflow items on to ground

### ISSUE THREAD

**Issue by Tealc-1899** [raiguard/Factorio-EditorExtensions#13]
When switching from editor mode to normal mode I am having items from my inventory spilling out on to the ground. Same way you would do when you take off a larger armour set and decreasing you inventory size.

This has been happening for the last few updates, but couldn't tell you from what version I first noticed it sorry.

I do have my inventory space increased via a command line.

It does not happen if "Sync inventory" is unchecked in the settings. Though I still have all the same items in my inventory (sync inventory still unchecked) when moving between modes with the only difference being that it stops items spilling on to the ground when returning to normal mode.

**Comment by raiguard** [comment]
Thanks, this has been fixed for the next release.
