### ISSUE TITLE
While in map editor mode, train schedule UI is offset to the right

### ISSUE THREAD

**Issue by Laogeodritt** [raiguard/Factorio-EditorExtensions#15]
While the map editor mode is enabled, the Train UI is offset to the right. Please see screenshots below.

Version information:

Factorio 0.18.22
Editor Extensions 1.4.1

Steps to reproduce:

1. Toggle the map editor ON.
2. Open a train that has a configured schedule.

Actual result:

![image](https://user-images.githubusercontent.com/1468874/82130631-1a963c80-979b-11ea-8832-f4fcb4ecffc3.png)

Expected result:

![image](https://user-images.githubusercontent.com/1468874/82130646-40234600-979b-11ea-9569-02d4e3fe9db4.png)

Notes:

* This bug does NOT occur with map editor mode turned off (i.e. normal gameplay with a character), even with the extension enabled.
* This bug does NOT occur in map editor mode with the extension disabled.
* This bug DOES occur in map editor mode with the extension enabled.

**Comment by raiguard** [comment]
This is happening because the infinity inventory filters are on. EE enables them by default, whereas in vanilla they have to be enabled after starting a new game.

Not a bug. Thanks for the report!
