### ISSUE TITLE
RaiLuaLib still mandatory

### ISSUE THREAD

**Issue by djubre7** [raiguard/Factorio-EditorExtensions#16]
It still asks for RaiLuaLib - tried to edit just the info.json but it spews an error when starting a new game - **doesn't crash the game**. Downloaded the latest RaiLuaLib from the mod portal (in addition to a Factorio library), so now it works as it should.

(Seablock 0.46, Factorio 0.18.18)

**Comment by raiguard** [comment]
If it's still asking for RaiLuaLib then you're not on the most recent version. You'll need to update your copy of Factorio as well, you're on a significantly outdated version there.
