### ISSUE TITLE
Crash when opening GUI for infinity loader

### ISSUE THREAD

**Issue by AndyMannnn** [raiguard/Factorio-EditorExtensions#17]
When clicking an infinity loader i get this crash:
![image](https://user-images.githubusercontent.com/67055581/85572034-f4cf4380-b634-11ea-9671-75fe59d13833.png)
 factorio version 0.18.33, editor extensions version: 1.5.6
save file:
[Design World.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/4825886/Design.World.zip)

**Comment by AndyMannnn** [comment]
turns out it also happens with the infinity accumulator:
![image](https://user-images.githubusercontent.com/67055581/85572841-a1a9c080-b635-11ea-8029-5ce0570ce5b8.png)

**Comment by raiguard** [comment]
Thanks, I'll fix this for the next version.

They changed up some GUI styles in .33 so I need to update my GUIs to match. This affects almost all of my mods.

**Comment by AndyMannnn** [comment]
okay, thanks :)

**Comment by raiguard** [comment]
The patch has been released.
