### ISSUE TITLE
Crash When Creating Entity Through Script

### ISSUE THREAD

**Issue by DedlySpyder** [raiguard/Factorio-EditorExtensions#18]
There is an incompatibility with the Powered Entities mod in a documentation scenario. Basically, my mod will generate a report for the player to tell them what my mod will work for. When EditorExtensions is also enabled though it will cause the following crash:

```
The mod Editor Extensions (1.5.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::script_raised_built (ID 77)
__EditorExtensions__/scripts/entity/infinity-loader.lua:72: attempt to index local 'entity' (a nil value)
stack traceback:
	__EditorExtensions__/scripts/entity/infinity-loader.lua:72: in function 'num_inserters'
	__EditorExtensions__/scripts/entity/infinity-loader.lua:203: in function 'create_loader'
	__EditorExtensions__/scripts/entity/infinity-loader.lua:465: in function 'on_built'
	__EditorExtensions__/control.lua:130: in function <__EditorExtensions__/control.lua:128>
```

This boils down to the `ee-infinity-loader-dummy-combinator` entity is created through my mod and raises the on script event, which then causes the crash. The following command can be used to cause the same error with only EditorExtensions enabled:

```lua
/c game.player.surface.create_entity{name="ee-infinity-loader-dummy-combinator", position={0,0}, raise_built=true}
```

**Comment by raiguard** [comment]
I ran the command but it didn't crash with just EE enabled. Downloading and running Powered Entities also doesn't cause a crash...

**Comment by DedlySpyder** [comment]
Hm, looks like that was kind of my fault, trying to put some logging into your mod and caused the issue, at least on just running the above command. It still failed when generating the report with my mod though (`/c remote.call("Powered_Entities", "build_report")`).

After some more tinkering on my end it looks like this is what was happening:

1. My mod tried to create a `ee-infinity-loader-dummy-combinator` and the `create_entity` returns nil
2. It really gets created and the loader is there (if you don't know anything on this end, then maybe this is a bug in Factorio? As far as I know it should only return nil if the entity wasn't created)
3. My mod tries to create a `ee-infinity-loader-logic-combinator` on the same spot, which then causes your mod to fail with the following error:
```
The mod Editor Extensions (1.5.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::script_raised_built (ID 77)
__EditorExtensions__/scripts/entity/infinity-loader.lua:72: attempt to index local 'entity' (a nil value)
stack traceback:
	__EditorExtensions__/scripts/entity/infinity-loader.lua:72: in function 'num_inserters'
	__EditorExtensions__/scripts/entity/infinity-loader.lua:193: in function 'create_loader'
	__EditorExtensions__/scripts/entity/infinity-loader.lua:455: in function 'on_built'
	__EditorExtensions__/control.lua:130: in function <__EditorExtensions__/control.lua:128>
```

Steps to reproduce (with just EditorExtensions activated), the first command should print the LuaEntity, but just prints `nil`:
```
/c game.player.print(serpent.line(game.player.surface.create_entity{name="ee-infinity-loader-dummy-combinator", position={0,0}, raise_built=true}))
/c game.player.surface.create_entity{name="ee-infinity-loader-logic-combinator", position={0,0}, raise_built=true}
```

Either way, I fixed this on my end by just moving on to the next position even if the build "fails". Though I am curious if this is a bug with `create_entity` then.

**Comment by raiguard** [comment]
So, the first command is returning `nil` because when you build a dummy combinator, EE immediately replaces it with a logic combinator, meaning that the original entity that you built no longer exists. This is necessary to make the infinity loader work, and there's no viable alternative.

The second command is crashing because you're building another loader on top of the first one. This is a problem on my end, since I didn't check if the loader was successfully built or not. I've fixed this by making the conversion into an actual loader silently fail if it isn't able to construct the loader. This will cause other problems, but at least it won't crash anymore!
