### ISSUE TITLE
Can't enable mod. probably mod conflict

### ISSUE THREAD

**Issue by wisnu-tunjangan** [raiguard/Factorio-EditorExtensions#23]
I can't enable the mod due to a mod conflict (doesn't know which one yet). the error log shows this

 137.961 Mods to disable:Failed to load mods: Error while running setup for entity prototype "ee-super-beacon" (beacon): next_upgrade target (beacon-2) must have the same fast_replaceable_group (bacon != beacon).

Mods to be disabled:
• EditorExtensions (1.5.20)

And somehow if hovercraft mod is enabled, it will also crash together with editor extension

Here's the log https://we.tl/t-Sg45LuiVLF
The link only active for one week

**Comment by hyodocraft** [comment]
here is the another log https://hastebin.com/raw/uwaseqazal
and the save file to sync mods https://drive.google.com/file/d/1YaG9hDYDiACFUGjmKnkZHL213viGeS6m/view?usp=sharing

**Comment by hyodocraft** [comment]
and the error is since "Version: 1.5.15" if I remember correctly

**Comment by raiguard** [comment]
This is a bug with ShinyBobGFX, you can see it [here](https://mods.factorio.com/mod/ShinyBobGFX/discussion/5f5fb7dd501271328e790dcf). Thanks for the reports!
