### ISSUE TITLE
Feature request: Adjustable-speed pumps

### ISSUE THREAD

**Issue by macdjord** [raiguard/Factorio-EditorExtensions#24]
When testing fluid systems, it would be helpful to be able to create pumps with maximum pumping speeds other than the default 12,000/s.

I therefore suggest adding a modded pump which has a GUI where the player can specify the desired maximum pumping rate. The GUI should accept the value in units per tick, per second, or per minute, and should accept non-integer values.

[There exist workarounds using an inifinity pipe connected to a pump to limit its flow rate](https://forums.factorio.com/viewtopic.php?p=513511#p513511), but:

- That requires an extra pipe segment attached to the pump; it would be far more natural to set the rate on the pump itself
- The infinity pipe segment acts as an infinite fluid source or sink; there is no way to rate-limit a pump in the middle of a fluid system.
- The workaround is restricted to incrementing the flow rate in multiples of 60 units/s up to a maximum of 6000 u/s; there is no way to, e.g., limit a pump to 30 u/s or 10,000 u/s.

**Comment by raiguard** [comment]
Factorio 1.1 will let you set infinity pipes to constantly add or remove a certain amount of liquid to/from themselves. This lets you test input or output rates, but does not let you rate-limit in the middle of a system. I will see about making it so pumps can have their speed changed at runtime.

**Comment by raiguard** [comment]
v1.6.0 was released yesterday, and included the new super pumps with an adjustable pumping speed! See the forum thread you linked for more information.
