### ISSUE TITLE
Feature request: Lowest-Priority Energy Consumption

### ISSUE THREAD

**Issue by CrusaderDeleters** [raiguard/Factorio-EditorExtensions#25]
I think the Infinity Accumulator should be able to be configured to draw power after all other entities. Currently, the only two options we have are primary (which draws energy before every other entity) and secondary (which draws energy in parallel with other entities on the connected energy network).

This system I'm proposing is key in being able to test energy generation facilities, more notably, Nuclear reactors.

As I've been testing my reactor, any time I request any amount of energy above sustainable, the power to the pumps reduce, which reduces flow coming from the heat exchangers to the turbines, which causes even less power generation, which quickly brings the system down. Instead, when using the Creative Mode Mod's Passive Power Void, it lets the pumps work as much as they need to before the rest of the power gets consumes, which will eventually stabilize into a lower power production mode, rather than into a completely-downed state.

**Comment by raiguard** [comment]
For some reason, I was under the impression that tertiary priority entities could only buffer power. But, turns out they can input or output power just fine as well. Implemented for the next release.

If I had known that when first making the IA, my life would have been a lot easier... SMH.

**Comment by raiguard** [comment]
Unfortunately, there is a slight problem: IAs that are set to tertiary will show their buffer size in the electric stats window as accumulator charge. I'll see if I can get that fixed for Factorio 1.1, as well as hiding the buffers completely for input and output type IAs.

**Comment by raiguard** [comment]
The buffers showing in the electric stats for input/output modes will be fixed in Factorio 1.1. In the meantime, just mentally subtract the size of the IA's buffer when looking at that figure.

The update will be released shortly.
