### ISSUE TITLE
Items filling extra MK2 armor slots are dumped on ground when closing the map editor

### ISSUE THREAD

**Issue by adamreiswig** [raiguard/Factorio-EditorExtensions#26]
#### Describe the Bug

I assume this is a bug. I have a MK2 armor equipped and any items in the 3 extra rows of slots it provides are dumped on the ground when I close the map editor. I've disabled all other mods and this continues. If I remove all items from those extra 30 slots, this behavior doesn't continue. Interestingly, the items are not removed from my inventory, just duplicated and dropped on the ground.

#### To Reproduce

1. Equip a MK2 Power Armor.
2. Fill your inventory completely. A variety of items makes it easier to see what is being dumped.
3. Open the map editor and then close the map editor.

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

I have no user/password on the file so I'm not sure which username is being requested here.

Upload the save file where the bug occurred
[EditorExt_Inventory_Dump.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/5285882/EditorExt_Inventory_Dump.zip)

. If the file is too large for GitHub, use an alternative file service.

Please also provide your in-game username so I can reproduce the conditions exactly.

_IF YOU DO NOT UPLOAD A SAVE FILE AND PROVIDE YOUR USERNAME, THE BUG REPORT WILL BE IGNORED UNTIL YOU DO._

#### Log file

Attach `factorio-current.log`, found in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/5285884/factorio-current.log)

**Comment by raiguard** [comment]
Thanks for the report, fixed for the next release.
