### ISSUE TITLE
Super Substation wire reach could be extended to 128 tiles.

### ISSUE THREAD

**Issue by mtaalas** [raiguard/Factorio-EditorExtensions#27]
Currently you need one super substation every 64 tiles even if the area provided is 128x128, this means that the areas of adjacent substations overlap by 64 tiles, and you need many times more of them if you want to create a large "testing area" that's provided with electricity for larger builds.

Could this be changed?

Currently it seems a bit arbitrary :)

**Comment by raiguard** [comment]
Unfortunately I cannot, as 64 is a hardcoded limit on the max distance between two power poles.sorry!

**Comment by mtaalas** [comment]
Dang it! Then we need a feature request for the devs :D
Thanks! :)
