### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dominiquini** [raiguard/Factorio-EditorExtensions#29]
#### Describe the Bug

When I tried to copy some recipe from a assembling machine and paste in the infinite loader (unintentionally), the game crash!

#### To Reproduce

1. Put an assembling machine and setup a recipe
2. Put an infinite loader
3. Copy the recipe of the assembling machine (SHIFT + Right Click)
4. Paste on the infinite loader (SHIFT + Left Click)

#### Save file & Username

Username: Dominiquini
Save File: I tested on the custom scenario of the Editor Extensions!

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/5330913/factorio-current.log)
![factorio_sVtj1S1WLi](https://user-images.githubusercontent.com/1180808/95148732-978a7880-0773-11eb-95a8-2ebfc4a65d79.png)

Thanks.

**Comment by raiguard** [comment]
While I am unable to reproduce the crash, I do know exactly what caused it and have fixed it for the next version. Thank you!
