### ISSUE TITLE
Unrecoverable error when changing mod settings

### ISSUE THREAD

**Issue by ZFrichtl** [raiguard/Factorio-EditorExtensions#3]
After loading a saved game (Factorio 0.18.9, Editor Extensions 1.2.1), and changing mod settings on the "Map" tab, I receive the following error after clicking on Resume:

<img width="378" alt="Screen Shot 2020-03-03 at 10 39 25 AM" src="https://user-images.githubusercontent.com/1790101/75820171-dda8d500-5d69-11ea-987b-82fdfc6d47b4.png">

**Comment by raiguard** [comment]
Thanks, this has been fixed for the next version.
