### ISSUE TITLE
creative chest idea

### ISSUE THREAD

**Issue by immortal-sniper1** [raiguard/Factorio-EditorExtensions#30]
#### Additional context

I'm always frustrated when: in a bot network i need to add 50+ items in the creative chests (heavy moded games )

 Describe the solution you'd like: maybe a sensor or chest that detects all the requests in that network (maybe with a button) so that all is there at the beginning and you can remove the intermediaries you make on site (like if you start from plates and what to make blue chips you have wire and c1 c2 s intermediaries but you can remove them from the request manualy since they are built in the setup

**Comment by raiguard** [comment]
Creative chests? Wrong mod! Just kidding, but they're infinity cheers. :)

Anyway, there are also aggregate chests that can help solve this problem. I've wanted a button to read logistic requests for a while now, so I'll probably add it. In the meantime, you'll either have to use an aggregate chest or set all the filters on a regular infinity chest.

**Comment by immortal-sniper1** [comment]
thx , atm i copied requests from assemblers to orange chests and it is working more or less after i added stuff manualy

**Comment by raiguard** [comment]
I think I've decided not to do this, it's not worth the runtime cost and effort required to add it.
