### ISSUE TITLE
Add a mapgen preset for playing with the editor.

### ISSUE THREAD

**Issue by sorahn** [raiguard/Factorio-EditorExtensions#31]
#### Describe the solution you'd like

Would be great if this mod could include a mapgen preset called 'Flatland' (or whatever) that defaults all the terrain features to off.  No trees/water/cliffs/ore/biters/pollution

Also if possible, could have it research all the tech as soon as the game starts.

**Comment by raiguard** [comment]
There is already something like this. Instead of choosing freeplay, look down and you'll see a mod scenario called "Testing". It spawns you into a lab world with a pre-built super bot setup, and enables cheat mode automatically. :)

**Comment by sorahn** [comment]
Oh snap! Totally missed that.  Thanks!!
