### ISSUE TITLE
Alternative "instant blueprint" mode

### ISSUE THREAD

**Issue by Till223** [raiguard/Factorio-EditorExtensions#35]
#### Is your feature request related to a problem? Please describe.

The normal map editor already provides a "instant blueprint" mode, but it doesn't work with the undo feature. From normal gameplay, I'm used to heavily rely on undo while tinkering with designs, so this always throws me off. It's especially annoying when I accidentally hit undo and remove some random entity somewhere on the map, leaving me wondering and terrified what just happened.

#### Describe the solution you'd like

An alternative "instant blueprint" mode that properly raises events and therefore works with undo. It will probably be much slower than the currently existing mode, but I don't care about performance in 99/100 cases and I can live with a few wasted seconds in that one instance.

#### Additional context

This has been reported as a bug already, but the devs don't seem to be interested in adjusting the existing mode:
https://forums.factorio.com/viewtopic.php?f=48&t=65683
I'm not sure what rseding is talking about here (maybe I'm missing something?), because I tried to implement this myself and it's surprisingly simple, here's my control.lua : 

```lua
script.on_event(defines.events.on_built_entity, function(event)  
    if event.created_entity ~= nil and (event.created_entity.type == "entity-ghost" or event.created_entity.type == "tile-ghost" ) then  
        event.created_entity.revive()  
    end  
end)  
```

From my quick testing, this already solves my issue and I could just keep it as a separate mod, however I thought it would make a good addition to editor extensions (I found this solution while writing this feature request, so I decided to finish it in case you're interested). Also thanks for making editor extensions! I've been using it ever since your [original release reddit post](https://www.reddit.com/r/factorio/comments/cno92v/introducing_infinity_mode_a_performancefriendly/) and it helped a ton with designing and testing all kinds of blueprints.

**Comment by raiguard** [comment]
Thanks for the suggestion, but I'm not going to be implementing scripted insta-blueprinting. I am annoyed by the editor lacking undo as well, but this mod is specifically designed to have as little scripting as possible.

There are other mods that add instant blueprinting via script, such as EasyCreative by Reika. If you want to fork EE and add it yourself for private use, you can reference the insta-blueprinting code from [Infinity Mode](https://github.com/raiguard/Factorio-InfinityMode/blob/41dd1098611c06682cdd4eaf146e220fa51436d3/src/scripts/util/conditional-event.lua#L18). Sorry!
