### ISSUE TITLE
Entity setting error

### ISSUE THREAD

**Issue by dennyh** [raiguard/Factorio-EditorExtensions#36]
#### Describe the Bug

Unrecoverable error happens when copying entity settings from a circuit connected inserter or belt to an infinity loader.
This happens when another mod is loaded as well. [Attach Notes](https://mods.factorio.com/mod/attach-notes)

#### To Reproduce

Run a game with mods:
[Attach Notes](https://mods.factorio.com/mod/attach-notes)
[Editor Extensions](https://mods.factorio.com/mod/EditorExtensions)

1. Place an inserter or a belt
2. Place any other entity able to connect to a circuit network wire.
3. Connect the enteties with a wire.
4. Place an infinity loader.
5. Copy (Shift+Right Click) the settings of the entity you placed in step 1.
6. Paste (Shift+Left Click) the settings on the infinity loader.
7. See error.

#### Save file & Username

Username: superdh
Save file: [BugTest.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/5482603/BugTest.zip)

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/5482604/factorio-current.log)

**Comment by raiguard** [comment]
Thank you for the report, this has been fixed for the next version.
