### ISSUE TITLE
Shift left/right click to copy settings from combinator to infinity loader

### ISSUE THREAD

**Issue by AmericanPatriot6f0** [raiguard/Factorio-EditorExtensions#37]
It is quite tedious to open all the menus in the infinity loaders, and set each ingredient that you want to go to your production line.
It would be nice if you could use the recipe/settings copy paste feature to set item filters on the loaders. If there were more than two items, the first two could be used and the rest ignored.

**Comment by raiguard** [comment]
Um, this is already a thing:

![image](https://user-images.githubusercontent.com/3515394/98332324-b28f1900-1fbb-11eb-969e-8c56f0fb3c3b.png)

**Comment by AmericanPatriot6f0** [comment]
Oops: there was an update I didn't have
