### ISSUE TITLE
Infinity Loader may stop unloading items

### ISSUE THREAD

**Issue by CrusaderDeleters** [raiguard/Factorio-EditorExtensions#39]
Copying the contents of an infinity loader with one filter may cause the loader to stop unloading onto belts entirely.

To reproduce, create this setup.
![image](https://user-images.githubusercontent.com/1791163/99415047-6ac69680-28c5-11eb-9564-fa5da62f7f4b.png)
Then, copy the contents of the top-right loader and paste it onto the bottom. After, copy the contents of the top-left loader and paste it onto the bottom. The unloaders should cease to work.

The username that I played on the map on was CrusaderDeleters
[Test.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/5554741/Test.zip)
[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/5554744/factorio-current.log)

**Comment by raiguard** [comment]
Thanks, this has been fixed for the next release. This was quite tricky to track down!
