### ISSUE TITLE
Infinity pipe auto config stopped working

### ISSUE THREAD

**Issue by danyax** [raiguard/Factorio-EditorExtensions#4]
In previous versions of mod when infinity pipe was build, it automatically sets liquid icon if connected to pipe network. In recent versions this no longer works, you have to manually select liquid.

In previous versions when infinity pipe was connected to input of a machine, it automatically sets level to 100%. Suggestion - set level of infinity pipe to 100% when it is connected to pipe network in which all connected machines are inputs.

**Comment by raiguard** [comment]
Hmm, thanks for the report. I never tested this after doing a bunch of refactoring, that's my fault. I'll get a patch out later today.

**Comment by raiguard** [comment]
Wooow, it was a really dumb mistake. Patch coming out in a few minutes. Thanks!

**Comment by raiguard** [comment]
Patch is out now. Infinity inserter autoconfig was also broken...
