### ISSUE TITLE
Missed renaming of "handlers" to "actions"

### ISSUE THREAD

**Issue by Choumiko** [raiguard/Factorio-EditorExtensions#40]
Noticed by accident, your util.close_button function still uses handlers instead of actions, which makes e.g. the super pump gui not close when clicking the button

https://github.com/raiguard/Factorio-EditorExtensions/blob/6316b77e62ac8e89c840f145aaf8df46929e31ec/src/scripts/util.lua#L55

**Comment by raiguard** [comment]
Oops, thank you!
