### ISSUE TITLE
Mod incompatibility

### ISSUE THREAD

**Issue by DocterDum** [raiguard/Factorio-EditorExtensions#41]
#### Describe the Bug

Modular life and EditorExtensions imcompatibility
Reported on both EE's Github and ModularLife's discussion
https://mods.factorio.com/mod/EditorExtensions
https://mods.factorio.com/mod/ModularLife

#### To Reproduce

Install EE and Modular Life, start game

#### Save file & Username
Issue occurs on startup, saves irrelevant

_IF YOU DO NOT UPLOAD A SAVE FILE AND PROVIDE YOUR USERNAME, THE BUG REPORT WILL BE IGNORED UNTIL YOU DO._

#### Log file
   0.001 2020-11-28 22:16:41; Factorio 1.0.0 (build 54889, win64, steam)
   0.001 Operating system: Windows 10 (version 1909) 
   0.001 Program arguments: "E:\SteamLibrary\steamapps\common\Factorio\bin\x64\Factorio.exe" "--wait-to-close" "9764" 
   0.001 Read data path: E:/SteamLibrary/steamapps/common/Factorio/data
   0.001 Write data path: C:/Users/Admin/AppData/Roaming/Factorio [9021/113826MB]
   0.001 Binaries path: E:/SteamLibrary/steamapps/common/Factorio/bin
   0.011 System info: [CPU: AMD FX(tm)-8350 Eight-Core Processor, 8 cores, RAM: 8376/16350 MB, page: 13689/20958 MB, virtual: 4328/134217727 MB, extended virtual: 0 MB]
   0.011 Display options: [FullScreen: 1] [VSync: 0] [UIScale: automatic (100.0%)] [Native DPI: 1] [Screen: 255] [Special: lmw] [Lang: en]
   0.018 Available displays: 1
   0.018  [0]: \\.\DISPLAY1 - AMD Radeon (TM) R9 390 Series {0x05, [0,0], 1920x1080, 32bit, 60Hz}
   0.173 [Direct3D11] Display: 0, Output: 0, DisplayAdapter: 0, RenderingAdapter: 0; d3dcompiler_47.dll
   0.289 Initialised Direct3D[0]: AMD Radeon (TM) R9 390 Series; id: 1002-67b0; driver: aticfx64.dll 27.20.14501.18003
   0.289   D3D Feature Level: 11.1, DXGI 1.5+, SwapChain: 3,flip-discard,-,-,-,none
   0.289   [Local Video Memory] Budget: 6942MB, CurrentUsage: 0MB, Reservation: 0/3675MB
   0.289   [Non-Local Vid.Mem.] Budget: 7357MB, CurrentUsage: 0MB, Reservation: 0/3883MB
   0.289   Tiled resources: Tier 2
   0.290   Unified Memory Architecture: No
   0.290   BGR 565 Supported: Yes
   0.290   MaximumFrameLatency: 3, GPUThreadPriority: 0
   0.298 Graphics settings preset: very-high
   0.298   Dedicated video memory size 8168 MB
   0.392 Desktop composition is active.
   0.392 Graphics options: [Graphics quality: high] [Video memory usage: all] [Light scale: 25%] [DXT: high-quality] [Color: 32bit]
   0.392                   [Max threads (load/render): 32/8] [Max texture size: 0] [Tex.Stream.: 0] [Rotation quality: normal] [Other: STDCWT] [B:0,C:0,S:100]
   0.467 DSound: Starting _dsound_update thread
   0.467 [Audio] Backend:default; Depth:16, Channel:2, Frequency:44100; MixerQuality:linear
   0.468 DSound: Enter _dsound_update; tid=10764
   0.603 Razer Chroma Controller initialized.
   0.663 Loading mod settings flib 0.5.0 (settings.lua)
   0.663 Loading mod settings ModularLife 0.3.2 (settings.lua)
   0.664 Loading mod settings EditorExtensions 1.7.5 (settings.lua)
   0.667 Loading mod core 0.0.0 (data.lua)
   0.839 Loading mod base 1.0.0 (data.lua)
   1.368 Loading mod flib 0.5.0 (data.lua)
   1.630 Loading mod ModularLife 0.3.2 (data.lua)
   1.912 Loading mod EditorExtensions 1.7.5 (data.lua)
   2.210 Loading mod base 1.0.0 (data-updates.lua)
   2.492 Loading mod ModularLife 0.3.2 (data-updates.lua)
   2.495 Error ModManager.cpp:1514: Failed to load mod "ModularLife": __ModularLife__/data-updates.lua:142: attempt to index field 'consumption' (a nil value)
stack traceback:
	__ModularLife__/data-updates.lua:142: in main chunk
   2.497 Loading mod core 0.0.0 (data.lua)
   2.661 Checksum for core: 3692526182
   2.779 Error ModManager.cpp:1514: Error in assignID: recipe-category with name 'crafting' does not exist.

Source: default (utility-sprites).
   2.906 Initial atlas bitmap size is 16384
   2.907 Created atlas bitmap 2048x560 [icon, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level]
   2.920 Texture processor created (2048). GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
   2.930 Parallel Sprite Loader initialized (threads: 7)
   2.966 Sprites loaded
   2.978 Generated mipmaps (5) for atlas [0] of size 2048x560   
   2.978 Custom mipmaps uploaded.
   2.984 Factorio initialised
   2.984 RivaTuner Statistics Server hook detected (rtsshooks64.dll)
   2.992 Mods to disable:Failed to load mods: __ModularLife__/data-updates.lua:142: attempt to index field 'consumption' (a nil value)
stack traceback:
	__ModularLife__/data-updates.lua:142: in main chunk

Mods to be disabled:
• ModularLife (0.3.2)
  17.437 Info AppManager.cpp:1226: Restarting Factorio
  17.499 Quitting: user-quit.
  17.628 Steam API shutdown.
  17.678 Goodbye

**Comment by raiguard** [comment]
This is the fault of Modular Life, not EE.

**Comment by DocterDum** [comment]
@raiguard 
See below - ee-super-clean-module uses the effectivity type, which in vanilla changes energy consumption, but doesn't change the effect.consumption value like a normal module would.
{
    name = "ee-super-clean-module",
    icon_ref = "module-3",
    order = "bd",
    category = "effectivity",
    tier = 50,
    effect = {pollution = {bonus = -2.5}},
    tint = {r = 0.4,g = 1,b = 1}
  },

For compatibility it might be better to add consumption = {bonus = 0} ?
Same applies for ee-super-dirty-module
Tested solution with Modular life and it works fine, also working on a compatibility suggestion for them

**Comment by raiguard** [comment]
It is not my fault if another mod is incapable of handling modded modules. Sorry, but I'm not going to add a useless property to deal with someone else's bad code. :)
