### ISSUE TITLE
Can't close infinity loader dialog by pressing X

### ISSUE THREAD

**Issue by rpdelaney** [raiguard/Factorio-EditorExtensions#42]
#### Describe the Bug

When setting an infinity loader, factorio 1.1.1 crashed with a stack trace:

```lua
The mod Editor Extensions (1.8.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::on_player_mined_entity (ID 65)
__EditorExtensions__/scripts/entity/infinity-loader.lua:551: attempt to index field 'handlers' (a nil value)
stack traceback:
	__EditorExtensions__/scripts/entity/infinity-loader.lua:551: in function 'destroy'
	__EditorExtensions__/control.lua:180: in function <__EditorExtensions__/control.lua:177>
```

#### To Reproduce

1. Go to [Location 433,237]
2. Click on infinity loader
3. Set infinity loader output to [item=iron-plate],[item=iron-gear-wheel]
4. Try to close the infinity loader dialog. It does not close.

When I first encountered this bug, I hit "X" many times in frustration before seeing stack trace above.

When reproducing it for this bug report, I find that I can close the dialog by left clicking on a nearby beacon.

#### Save file & Username

- [x] Upload the save file where the bug occured. If the file is too large for GitHub, use an alternative file service.

[_autosave3.tar.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/5611168/_autosave3.tar.zip)

- [x] Please also provide your in-game username so I can reproduce the conditions exactly.

`AnEntireSleeve`

#### Log file

- [x] Attach `factorio-current.log`, found in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

[factorio-current.log.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/5611167/factorio-current.log.zip)

**Comment by raiguard** [comment]
Thanks. I had already fixed the close buttons for the next version, but didn't find that crash! The crash is now fixed as well :)
