### ISSUE TITLE
`Value must be a dictionary in property tree at ROOT.parameters` when copy-pasting from an infinity pipe

### ISSUE THREAD

**Issue by rpdelaney** [raiguard/Factorio-EditorExtensions#43]
#### Describe the Bug

When copy-pasting settings from an infinity pipe to a constant combinator:

```lua
The mod Editor Extensions (1.8.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::on_entity_settings_pasted (ID 31)
Value must be a dictionary in property tree at ROOT.parameters
stack traceback:
	[C]: in function '__newindex'
	__EditorExtensions__/control.lua:256: in function <__EditorExtensions__/control.lua:224>
```

#### To Reproduce

1. Go to 464,282
2. Shift+right click on the infinity pipe producing lubricant to copy
3. Shift+left click on the constant combinator next to the pipe to paste

#### Save file & Username

- [x] Upload the save file where the bug occurred. If the file is too large for GitHub, use an alternative file service.

[sandbox2.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/5611462/sandbox2.zip)

- [x] Please also provide your in-game username so I can reproduce the conditions exactly.

`AnEntireSleeve`

#### Log file

- [x] Attach `factorio-current.log`, found in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

[factorio-current.log.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/5611463/factorio-current.log.zip)

**Comment by raiguard** [comment]
Wow, you're finding all sorts of mistakes that I made when porting the mod to 1.1. Thank you! Fixed for the next version. :)

**Comment by rpdelaney** [comment]
I use the mod a lot in sandbox mode, so it's easy ;) Thanks for your work on this. My blueprints thank you
