### ISSUE TITLE
Crash on opening Infinity Wagon

### ISSUE THREAD

**Issue by MrBadDragon** [raiguard/Factorio-EditorExtensions#44]
When clicking on an infinity wagon I get the following fatal crash

The mod Editor Extensions (1.9.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::on_gui_opened (ID 84)
__EditorExtensions__/scripts/entity/infinity-wagon.lua:90: attempt to index local 'player' (a number value)
stack traceback:
	__EditorExtensions__/scripts/entity/infinity-wagon.lua:90: in function 'open'
	__EditorExtensions__/control.lua:381: in function <__EditorExtensions__/control.lua:358>

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/5706870/factorio-current.log)

**Comment by raiguard** [comment]
Thanks, fixed for the next release.
