### ISSUE TITLE
Linked chest channels

### ISSUE THREAD

**Issue by tkozyrski** [raiguard/Factorio-EditorExtensions#46]
Please implement link chest's channels, similar to AAI Signal Transmission (https://mods.factorio.com/mod/aai-signal-transmission). Instead of using checkboxes use channels (chest) names.

**Comment by raiguard** [comment]
Linked chests are a vanilla entity, and the channel picker is vanilla as well. It's not very high on my priority list to add an alternate channel picker. But I'll think about it.

**Comment by tkozyrski** [comment]
Schall did something similar in his mod (https://mods.factorio.com/mod/SchallAutolinkedChest).

**Comment by tkozyrski** [comment]
How about generating unique identifier each time a chest is created and checking correspoinding boxes by itself? Again, that what Shall did, it would vastly improve the use of linked chests.

**Comment by raiguard** [comment]
I honestly find the checkboxes to be intuitive enough. If you need to link two chests and can't remember the combo, just copy/paste from one chest to the other.
