### ISSUE TITLE
Don't leave invalid prototypes around between data stages 🙏

### ISSUE THREAD

**Issue by theRustyKnife** [raiguard/Factorio-EditorExtensions#47]
I'm specifically talking about the item `ee-linked-belt` as it relates to [this crash](https://mods.factorio.com/mod/crafting_combinator/discussion/5fdfc2533cc4747e7fc0724a). The problem is that it's created in data, but [this line](https://github.com/raiguard/Factorio-EditorExtensions/blob/696e73587fc6025e649b3d01748b90f480f9fa78/src/prototypes/item.lua#L133) sets it's `place_result` to `ee-linked-belt-express`, which is only created in data-final-fixes by [this line](https://github.com/raiguard/Factorio-EditorExtensions/blob/696e73587fc6025e649b3d01748b90f480f9fa78/src/data-final-fixes.lua#L141) (assuming the express belt exists, which is potentially a whole another issue).

This leaves any mods running in between these two stages with invalid prototypes, causing problems like the one mentioned above. It's also just bad manners, though that's hardly an objective argument :smile: 

The above crash can be reproduced by simply installing the following three mods along with this one: [Rusty Locale](https://mods.factorio.com/mod/rusty-locale), [Transport Drones](https://mods.factorio.com/mod/Transport_Drones) and [Crafting Combinator](https://mods.factorio.com/mod/crafting_combinator). The explanation for why it's not a fault of any of those mods is in the linked post.

I managed to fix this particular crash by setting the `place_result` to `nil`, though I'm not familiar enough with the mod to say if that's an adequate solution or not... Another solution would be adding an optional dependency to Crafting Combinator, though that would be fixing the symptoms, rather than the root cause, so I'd rather avoid it.

Given the threatening sentence in the issue template, I feel obligated to mention that save files, usernames and log files are completely irrelevant to this issue :smile:

**Comment by raiguard** [comment]
Thanks for the report. I've gone ahead and added code to dynamically set the `place_result` of that item to the fastest detected belt type, instead of it being hardcoded. This applies to the infinity loader as well.
