### ISSUE TITLE
Non-recoverable error

### ISSUE THREAD

**Issue by obtitus** [raiguard/Factorio-EditorExtensions#48]
#### Describe the Bug

Get a unrecoverable error when placing my first infinite loader on my first map

#### To Reproduce

Have not checked if this is re-producable. but:

1. Started a new game
2. Went into editor extension mode ctrl-e
3. placed the first, of (two identical looking??) infinite loaders

Error while running event EditorExtensions::on_built_entity (ID 6)
__EditorExtensions__/scripts/entity/infinity-loader.lua:186: attempt to concatenate local 'type' (a nil value)
stack traceback:
	__EditorExtensions__/scripts/entity/infinity-loader.lua:186: in function 'create_loader'
	__EditorExtensions__/scripts/entity/infinity-loader.lua:428: in function 'build'
	__EditorExtensions__/control.lua:217: in function <__EditorExtensions__/control.lua:203>

#### Save file & Username

Let me know if you need this, this was an empty game.

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/5740675/factorio-current.log)

**Comment by raiguard** [comment]
Sorry, fixed for the next release.

**Comment by obtitus** [comment]
Thanks for the quick fix, works great now. This was my first time using the mod, placing down my first item, so pretty bad luck!

**Comment by raiguard** [comment]
Well, I'm sorry for that first experience! I promise my mods aren't this buggy all the time. :)
