### ISSUE TITLE
set infinity pipe percent to either 50 or 100% when copying settings from a combinator

### ISSUE THREAD

**Issue by AmericanPatriot6f0** [raiguard/Factorio-EditorExtensions#49]
When one copies the filter from a combinator to a pipe, they almost never want it to consume fluid: they are setting the inputs of a  subfactory. Manually changing the settings can become very tedious when done often.

If the pipes were by default set to 100% (or, if you desire the possibility of pipe consumers to remain open, 50%) then the tedium of  manually setting pipe filters would be eliminated.

**Comment by raiguard** [comment]
Well, pipes don't need filters to consume, so I'll just set it to produce at 100%. Thanks for the suggestion!
