### ISSUE TITLE
Enhancement - add search for fluid selection window

### ISSUE THREAD

**Issue by danyax** [raiguard/Factorio-EditorExtensions#5]
When selecting fluid in infinity pipe in Angel Bob game, it is takes some time to find correct fluid among around hundred available fluids. Search function would be nice.

**Comment by raiguard** [comment]
The infinity pipe is actually a vanilla entity, I don't have any control over its GUI. It does seem weird that it's missing a search button though, everything else in the game has one.

I'll request this on the Factorio forums to be added to the base game. Thank you!
