### ISSUE TITLE
Enable research queue in the mod scenario

### ISSUE THREAD

**Issue by ekevoo** [raiguard/Factorio-EditorExtensions#50]
Problem: I have to enable research queue when I start a new map to test science per minute builds.

Solution: Auto-enable research queue in the Editor Extensions/Testing scenario.

**Comment by raiguard** [comment]
Just tested it, and it's enabled by default for me. Make sure you're on the latest version.

**Comment by ekevoo** [comment]
Yeah, probably because I was still in 1.0. Can confirm that it's fixed.
