### ISSUE TITLE
Mod not loading on headless multiplayer

### ISSUE THREAD

**Issue by oof2win2** [raiguard/Factorio-EditorExtensions#51]
#### Describe the Bug

Mod not being loaded on headless multiplayer. The mod is shown in `mod-list.json` as `true` (enabled), it is in the ./mods directory but it isn't enabled/loaded when the game runs.
The mod seemingly loads fine on the same save on a headed game and on the same save.
Other mods load and run completely fine on the same server at the same time, see the log below.
Info: This save has been started in singleplayer, then has been transferred to a headless server for multiplayer, where it doesn't work.

#### To Reproduce

Using Factorio 1.1.8 & mod version 1.9.5

1. Download the mod onto a headless server, enable it in `mod-list.json`
2. Run the game
3. Mod doesn't show as enabled

#### Save file & Username

[testMap.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/5791165/testMap.zip)
My in-game name is `oof2win2`.
If needed, here is the `mod-list.json` file (converted to .txt for github upload)
[mod-list.txt](https://github.com/raiguard/Factorio-EditorExtensions/files/5791174/mod-list.txt)

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/5791166/factorio-current.log)

**Comment by raiguard** [comment]
Does the server also have flib? EE requires it in order to run.

**Comment by oof2win2** [comment]
Yup, that's the issue! Forgot to check for any requirements. Thanks!
