### ISSUE TITLE
Fails to load Mod Scenario along side Angels Petrochem

### ISSUE THREAD

**Issue by robertsonj3** [raiguard/Factorio-EditorExtensions#52]
#### Describe the Bug
When starting a new game, Scenario 'Editor Extensions/Testing' the migration will fail if Angels Petrochem is also enabled.
Sorry, not sure if this is an issue in extension or petrochem.

```
Error while applying migration: Angel's Petrochemical Processing: angelspetrochem_0.4.0.lua

__angelspetrochem__/migrations/angelspetrochem_0.4.0.lua:13: attempt to index field 'chemical-plant-2' (a nil value)
stack traceback:
	__angelspetrochem__/migrations/angelspetrochem_0.4.0.lua:13: in main chunk
```

#### To Reproduce

- Enable Mods (And dependencies):
  - Angel's Petrochemical Processing - 0.9.17
  - Angel's Refining- 0.11.19 
  - Editor Extensions - 1.9.5
  - Factorio Library - 0.6.1
- On main menu
  - Click 'Single Player'
  - Click 'New Game'
  - Select 'Editor Extensions/Testing'
  - Click 'Play'

#### Save file & Username

The bug occurs before a save can be produced.

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/5807691/factorio-current.log)

#### Linked Report in Petrochem

[https://forums.factorio.com/viewtopic.php?p=531818#p531818](url)

**Comment by raiguard** [comment]
As far as I can tell, this is an issue with petrochem, not EE.

**Comment by robertsonj3** [comment]
Cheers, I'll follow up with petrochem. Thanks for looking into it.
