### ISSUE TITLE
Smol error when placing infinity loaders next to miniloaders

### ISSUE THREAD

**Issue by Purpzie** [raiguard/Factorio-EditorExtensions#53]
#### Describe the Bug
This doesn't cause any harm besides the error message. It can still be manually positioned to connect to the miniloader, and it works exactly as expected.

![Capture](https://user-images.githubusercontent.com/25022704/105429927-0fdc5300-5c18-11eb-80c4-4f1f6e523545.PNG)

#### To Reproduce
1. Place a [miniloader](https://mods.factorio.com/mod/miniloader)
2. Place an infinity loader next to it

#### Save file & Username
The bug is so small that a save file doesn't seem required. If it is, please let me know and I'll add it here ASAP.

#### Log file
There's nothing in there about the error it seems, but [here it is just in case.](https://github.com/raiguard/Factorio-EditorExtensions/files/5852894/factorio-current.log)

**Comment by raiguard** [comment]
Thanks, fixed for the next release.
