### ISSUE TITLE
Undo infinity loader doesn't

### ISSUE THREAD

**Issue by dirk-bester** [raiguard/Factorio-EditorExtensions#54]
The infinity loader does not undo its placement like everything else.

#### To Reproduce
1) Place an infinity loader or paste it or blueprint it.
2) Press Undo
3) Everything gets reverted, the infinity loader remains.

#### Save file
No included save file, it has been doing this for a while and still does it with the latest update in 1.1.19. It is not a file based bug, its an editor bug. A save file cannot demonstrate the bug.

#### Log file
Clean run with only editor extensions and its dependency enabled. Tested on map editor of the lab floor scenario from editor extensions. Apparently you need to open the editor one time before it will undo properly.
[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/5884506/factorio-current.log)

**Comment by raiguard** [comment]
This is unavoidable, the mod replaces the entity that you place with a different one. There is no way to interface with the undo system so it is what it is. Sorry!
