### ISSUE TITLE
Blueprint

### ISSUE THREAD

**Issue by Mattia2510MC** [raiguard/Factorio-EditorExtensions#55]
#### Describe the Bug

Game Crashed while creating a blueprint

#### To Reproduce

~~I was creating a blueprint using a black one found inside a book in the blueprint manager~~
See comment

#### Save file & Username

The bug happened on a newly created map, where I was doing some testing. Since I disable autosave on testing maps, neither save nor autosave are available.

Username: Mattia2510

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/5975634/factorio-current.log)

**Comment by Mattia2510MC** [comment]
Found a reliable way to reproduce:
1. Open a save (I used the debugging one, but any will do)
2. Place a blueprint book in the inventory
3. Place a blank blueprint in the book
4. Select something with the book and have SHIFT held down
5. Error

The bug doesn't occur when using SHIFT with just a blueprint, but only when the blueprint is inside a book

**Comment by raiguard** [comment]
Thanks for the report, fixed for the next release.
