### ISSUE TITLE
Inverted Aggregate Chest

### ISSUE THREAD

**Issue by Mattia2510MC** [raiguard/Factorio-EditorExtensions#56]
#### Is your feature request related to a problem? Please describe.

When designing a base I usually place down a passive aggregate chest. When I finally have and item produced, I usually just remove that item from the chest GUI. Now that you have removed that possibility, I no longer have a way to have a global robot network with an aggregate chest in it

#### Describe the solution you'd like

I suggest adding an inverted aggregate chest. If you set an item in the filter, that item will no longer be generated

**Comment by raiguard** [comment]
I only disabled the infinity filters on aggregate chests because I didn't think anyone used them. Additionally, they are reset whenever mod configuration changes.

I guess I can add a mod setting to enable them, so those who actually did use them can still do so. Sorry!

**Comment by raiguard** [comment]
I added a setting to re-enable aggregate chest filters.
