### ISSUE TITLE
Please set default infinity pump speed to a number greater than or equal to normal pump.

### ISSUE THREAD

**Issue by AmericanPatriot6f0** [raiguard/Factorio-EditorExtensions#57]
I'm always frustrated when I put down an infinity pump, only to realize that it is set to 1000ps. I have never encountered a time when I only wanted 1000 fluid per second and usually just replace the pump with a vanilla pump + energy interface.

I would be very pleased if the infinity pump speed was set to the maximum, or at least 12000ps by default.

**Comment by raiguard** [comment]
Ok, I set it to 12,000 by default.
