### ISSUE TITLE
Interaction with Picker mods

### ISSUE THREAD

**Issue by danyax** [raiguard/Factorio-EditorExtensions#6]
Picker mod has following feature: Ctrl-Q over any entity created temporary blueprint in hand that can be stamped. For some reasons when pressing Ctrl-Q over infinity loader something goes wrong, blueprint is created but it is barely visible and does not stamp properly. I play with Creative mod and instant blueprint in Creative are enabled, editor mode is off.

**Comment by raiguard** [comment]
I you're using creative mod then why are you also using editor extensions? You'd probably be better served just using one or the other. ;)

I'll look into it, thanks for the report!

**Comment by raiguard** [comment]
Initial investigation has revealed that picker blueprinter just naively picks up whatever entity you're hovering over, and it doesn't provide a remote interface. In other words, there's nothing I can do about it. It does work, you just have to place it, pick the ghost, and place it again. Sorry!
