### ISSUE TITLE
Ability to fill player's infinity filters via LUA code

### ISSUE THREAD

**Issue by saaadel** [raiguard/Factorio-EditorExtensions#60]
#### Is your feature request related to a problem? Please describe.

I want to fill player's infinity filters via console.

#### Describe the solution you'd like

How can I do that? I mean some kind of table for that:
```
local first_player = game.get_player(1)
first_player.infinity_filters[item_name_var]={ atMost: 100 }
-- or
first_player.infinity_filters[item_name_var]={ atLeast: 10 }
-- or
first_player.infinity_filters[item_name_var]={ exactly: 50 }
```

#### Additional context
--

**Comment by raiguard** [comment]
There is already an API to do it.

[LuaPlayer::infinity_inventory_filters](https://lua-api.factorio.com/latest/LuaPlayer.html#LuaPlayer.infinity_inventory_filters). Infinity inventory filters are a vanilla feature, but are disabled by default for some reason. EE just enables them by default.
