### ISSUE TITLE
Add a new settings option (Map Editor popup): Instant ghosts building

### ISSUE THREAD

**Issue by saaadel** [raiguard/Factorio-EditorExtensions#61]
#### Is your feature request related to a problem? Please describe.

I want to build near ghosts on the screen (or in radius NxN from mod options)

#### Describe the solution you'd like

Add a new settings option (Map Editor popup): "Instant ghosts building"
And replace all near ghosts to its items, like for blueprints.

#### Additional context

--

**Comment by raiguard** [comment]
The map editor already does this automatically, and there is a settings tab in the map editor if you want to disable it.

**Comment by saaadel** [comment]
but it does not do that:
it has a instant blueprints building, when I place the item ghost in the editor mode.
But this does not works for already placed ghosts, when I moved over them - they still kept as ghosts (with all options enabled)

**Comment by raiguard** [comment]
Oh, sorry, I didn't understand your description the first time.

That sounds like [Mouse-over construction](https://mods.factorio.com/mod/MouseOverConstruction), which is another mod of mine. It doesn't currently place things for free if you're in the editor, but I can add that feature to it.

**Comment by saaadel** [comment]
sounds good, but it will be too slow if we have a lot of ghosts already placed on the ground.
