### ISSUE TITLE
Cannot set infinity filters in multiplayer mode

### ISSUE THREAD

**Issue by Karl-D-Asmussen** [raiguard/Factorio-EditorExtensions#62]
#### Describe the Bug

When playing multiplayer sandbox mode over LAN, I can create infinity chests, but I cannot configure the infinity filter — no tab appears in the chest inventory screen. The host of the game can set the infinity filters no problem.

#### To Reproduce

1. Play Factorion version 1.1.30
2. Use Editor Extensions version 1.9.11, Factory Planner version 1.1.9
3. Host a new LAN game in Sandbox mode
4. Join that game as a client
5. As client, enable cheat mode when prompted
6. Create an infinity chest item
7. Place infinity chest
8. Open infinity chest inventory as host to see infinity filter tab
9. Open infinity chest inventory as client and observe its absence

#### Save file & Username

Username: `everything-narrative`

Save file: [sandbox2.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/6229524/sandbox2.zip)
(Works with a fresh save. Provided save file is a lab-tiled world with a single infinity chest placed by client.)

Log file: [factorio-previous.log](https://github.com/raiguard/Factorio-EditorExtensions/files/6229520/factorio-previous.log)

**Comment by raiguard** [comment]
It's because only admins can change infinity chests by default. I kept this setting on purpose, but it doesn't make sense for people to be able to place infinity chests but not be able to modify them. I'll change it for the next version.
