### ISSUE TITLE
Instant Undo for Editor/Cheat-Mode

### ISSUE THREAD

**Issue by NotRexButCaesar** [raiguard/Factorio-EditorExtensions#63]
#### Is your feature request related to a problem? Please describe.

Whenever undoing a mining or deconstruction operation, it is slightly annoying to have to copy-paste the ghosts over themselves. 

#### Describe the solution you'd like

I would like the undo operation to place real entities, rather than ghosts.

**Comment by raiguard** [comment]
Unfortunately, there's no good way to do this. It's not going to happen unless the devs make it a vanilla feature (which, IMO, they really should).
