### ISSUE TITLE
Crash on opening infinity accumulator GUI

### ISSUE THREAD

**Issue by Majoca22** [raiguard/Factorio-EditorExtensions#64]
#### Describe the Bug

When you click on an infinity accumulator to open its GUI, the game crashes. Crash report:

The mod Editor Extensions (1.9.11) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::on_gui_opened (ID 85)
Unknown style flib_titlebar_flow
stack traceback:
	[C]: in function 'add'
	__flib__/gui-beta.lua:42: in function 'recursive_build'
	__flib__/gui-beta.lua:87: in function 'recursive_build'
	__flib__/gui-beta.lua:107: in function 'build'
	...itorExtensions__/scripts/entity/infinity-accumulator.lua:85: in function 'create_gui'
	...itorExtensions__/scripts/entity/infinity-accumulator.lua:308: in function 'open'
	__EditorExtensions__/control.lua:382: in function <__EditorExtensions__/control.lua:365>

#### To Reproduce

1. Factorio on version 1.1.30
2. No mods other than Editor Extensions 1.9.11 (and FLib)
3. Start a new EE testing scenario map
4. Click on the infinity accumulator

#### Save file & Username

Save file: [EE crash.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/6301098/EE.crash.zip)

Username: `majoca`

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/6301109/factorio-current.log)

**Comment by raiguard** [comment]
I apprently forgot to update EE's `flib` dependency. Update the `Factorio Library` mod and the crash will be fixed.
