### ISSUE TITLE
Cannot set Infinity Fluid Wagon filters in multiplayer mode

### ISSUE THREAD

**Issue by Karl-D-Asmussen** [raiguard/Factorio-EditorExtensions#66]
#### Describe the Bug

Identical problem to #62 except applies to Infinity Fluid Wagons.

#### To Reproduce

Follow the same steps as in #62 except with an Infinity Fluid Wagon.

#### Save file & Username

Should be unnecessary, I think you already know exactly how to fix this.

Username: `everything-narrative`

[Blank.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/6372113/Blank.zip)

Note: this is the exact map where the error occurred, not a minimal reproduction, there's some infinity fluid wagons in it somewhere if you can find them — good luck!

#### Log file

Should be unnecessary, I think you already know exactly how to fix this.

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/6372123/factorio-current.log)

**Comment by raiguard** [comment]
Sorry about that. Fixed for the next version.

**Comment by Karl-D-Asmussen** [comment]
@raiguard Thank you for the fast response!
