### ISSUE TITLE
Additional circut network modes for infinity chests

### ISSUE THREAD

**Issue by CentaurPrime** [raiguard/Factorio-EditorExtensions#68]
#### Is your feature request related to a problem? Please describe.

I have been playing around with the editor extensions while building some generic blueprints, and I found myself building a test infrastructure using infinity chests. Depending on the recipe configured in the assemblers, I find myself in need of different filters in the chests used for loading. Rather than performing a copy/paste operation to change the filter on each of 50+ infinity chests, I find myself wishing I could specify the filter to use using a constant combinator. This would allow a fast reconfiguration of chests in a single place.

#### Describe the solution you'd like

Add the following modes to the circuit network selector for the different types of infinity chests:
* Filter at least
* Filter exactly
* Filter at most

Setting the circuit network mode to one of these values would be equivalent to setting the infinity filters on the chest to filter in the mode identified for each signal specified on the circuit network at the value specified for the signal. This would likely be one of those options that could cause performance penalties, so the warning boilerplate might be needed.

#### Additional context

As an example, sending an 'iron plate' signal with a value of '100' to an infinity chest with a mode of 'Filter at least' would result in the the same behavior as if the set of filters on the chest had been set to at least 100 iron plate.

**Comment by raiguard** [comment]
I'm not sure I want to do this. It would be useful, but it would be insanely performance-heavy. I think it would be much better to petition the devs to add this to the infinity chest natively. Sorry!
