### ISSUE TITLE
Infinity loader next to miniloader - issue with yellow tier only

### ISSUE THREAD

**Issue by kryojenik** [raiguard/Factorio-EditorExtensions#69]
Factorio 1.1.35
EditorExtensions 1.9.13
boblogistics 1.1.3

This appears to be a remaining manifestation of #53.  With Bob's Logistics, all mini-loaders attach without error except for the yellow tier. 

![image](https://user-images.githubusercontent.com/845427/122411767-a2c0b580-cf4a-11eb-9263-7b42d5a04a43.png)

Assuming:
Grey: Basic
Yellow: \<no tier label\>
Ref: Fast
Blue: Express
Purple: Turbo
Green: Ultimate

![image](https://user-images.githubusercontent.com/845427/122411576-7a38bb80-cf4a-11eb-82dc-860ebd5fe18b.png)

Place miniloader or filter miniloader, place infinity loader adjacent.

**Comment by raiguard** [comment]
Thanks, fixed for the next release.
