### ISSUE TITLE
Allow Infinity Chest variants to be upgradable to other chests

### ISSUE THREAD

**Issue by PiggyWhiskey** [raiguard/Factorio-EditorExtensions#70]
Currently EE Chests can only be upgraded to other EE Chests.

Can I request this be changed to allow the upgrade planner to change it to any other chest (Like the vanilla Logistic Chests)

**Comment by raiguard** [comment]
I just looked, and you can already do that.

![image](https://user-images.githubusercontent.com/3515394/125540209-9b8e04bf-ca73-45db-b4bd-4a768296d5c4.png)
