### ISSUE TITLE
Wagon Speed Cap

### ISSUE THREAD

**Issue by Garr890354839** [raiguard/Factorio-EditorExtensions#71]
#### Is your feature request related to a problem? Please describe.

Yes: It would seem as if the wagons this mod provides are capped at 324km/h. The locomotive provided goes way faster than 324km/h.

#### Describe the solution you'd like

Should be as simple as changing the speed value on wagons to be 2160km/h.

**Comment by raiguard** [comment]
Ok, added for the next version.
