### ISSUE TITLE
Creation of a blueprint with "Infinity cargo wagon" doesn't keep the "Remove unfiltered items" flag

### ISSUE THREAD

**Issue by Telkine2018** [raiguard/Factorio-EditorExtensions#73]
#### Describe the Bug

The  "Remove unfiltered items" flag is lost when creating a blueprint with an "Infinity cargo wagon" 

#### To Reproduce

1. Add an "Infinity cargo wagon" with "Remove unfiltered items" flag on
2. Add it to a blueprint
3. Put the blueprint on map
4. The "Remove unfiltered items" flag is off

**Comment by raiguard** [comment]
Hmm, this seems like a bug with Factorio itself. I will open a bug report with the Factorio developers.

**Comment by raiguard** [comment]
Thanks, fixed for the next version.
