### ISSUE TITLE
Missing belts and inserters in Aggregate Chest with specific mod combination

### ISSUE THREAD

**Issue by kryojenik** [raiguard/Factorio-EditorExtensions#74]
#### Describe the Bug

There is an interaction with a specific mod combination:

https://mods.factorio.com/mod/angelsindustries
https://mods.factorio.com/mod/boblogistics
https://mods.factorio.com/mod/DeadlockStackingForAngels
and of course
https://github.com/raiguard/Factorio-EditorExtensions

Of course all dependencies are required as well.

When these three mods are loaded along with Editor Extensions, the aggregate boxes of Editor Extensions will not contain belts and inserters.  Therefore, the super-robots can't build things.  This can be worked around by placing an Infinity Passive Provider and explicitly adding belts and inserters to the Infinity Filters.

If you remove any one of the above three mods (and leave the dependencies) the issue does not manifest.

#### To Reproduce

Create new game with the above list of mods
Place a super roboport and add super constructions robots
Place an aggregate provider chest
Place ghost belts or inserters.  The belts and inserters will not get built, Other entities will.
Reviewing the items in the Aggregate chest does not show belts or inserters.

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

User name in the save file is kryojenik
[EE-Test.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/6919863/EE-Test.zip)

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/6919869/factorio-current.log)

**Comment by kryojenik** [comment]
Pipes appear to be missing too

**Comment by raiguard** [comment]
Thanks for the report. DeadlockStackingForAngels was adding stuff after Editor Extensions defined the aggregate chest. I simply added that mod as a hidden dependency, and that fixed it.
