### ISSUE TITLE
Unable to identify belt type.

### ISSUE THREAD

**Issue by CaitSith2** [raiguard/Factorio-EditorExtensions#76]
Was playing around with Editor extensions, and upon mating the linked belt or infinity loader with the belts contained in [url=https://mods.factorio.com/mod/BetterBelts]Better Belts[/url],  I get told 'Please report the following information to the mod author on GitHub: entity_name = "BetterBelts_ultra-transport-belt", parse_result = "BetterBelts_ultra".

**Comment by nicolas-lang** [comment]
Same for K2 loaders.

entity_name = "kr-loader", parse_result = "kr".

**Comment by raiguard** [comment]
Implemented for the next release.
