### ISSUE TITLE
game crash: switching to editor with blueprint in hand.

### ISSUE THREAD

**Issue by Patrick-KL** [raiguard/Factorio-EditorExtensions#78]
#### Describe the Bug
 
Switching to editor mode while holding a blueprint crashes the game.

#### To Reproduce

1. grab hold of a blueprint in your hands, so you see the build overlay on your screen.
2. switch to the editor mode using the bottomright shortcut.
3. game crashes.

#### Save file & Username

[Space Exploration.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/7428380/Space.Exploration.zip)

My username is Falknire.

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/7428386/factorio-current.log)

**Comment by raiguard** [comment]
Thanks for the report. However, I am unable to reproduce the issue using the save and steps provided. Do you have a 100% consistent way to reproduce it?
