### ISSUE TITLE
large BlueprintBooks vanish in InventorySync

### ISSUE THREAD

**Issue by Calibretto22** [raiguard/Factorio-EditorExtensions#8]
I have rather large Blueprint-Books in my game. 
With the new Feature "Inventory sync" some books are reliably destroyed, when switching in editor-mode. 

This does not happen when Sync is disabled. 

Perhaps you can announce the feature and this downside a bit more prominently. 

Also: syncing of inventoryfilters would be great. 

Link: [savegame where books vanish reliably.](https://drive.google.com/open?id=1oO7OupqFT7gbv7XnQ_xVnsh1ld5_6iwd)

**Comment by raiguard** [comment]
Thanks for sending a save game, I'll look into it.

**Comment by raiguard** [comment]
Geez... with that many blueprint books, syncing the inventories takes _forever!_ I would recommend keeping those in the blueprint library instead to make syncing far more performant.

As for syncing inventory filters, that is impossible. Inventory filters only exist in the map editor, so there's nothing to "sync" at all. Sorry!

**Comment by Calibretto22** [comment]
Thanks for looking into it. 
It could be, that I did not enter the editor for some time. Today was the first time I noticed the considerable lag, when entering the editor. Since the lag did not occur when the game was vanilla I started looking for options in the mods. 

(in my first comment I meant the slot filters)

For now i just disabled the sync. That's fine for me. 

Thanks for the great mod.

**Comment by Calibretto22** [comment]
(it's okay if you want to close the issue.)

**Comment by raiguard** [comment]
I'll close this once I fix the bug :D

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/82261360-15143000-991c-11ea-9e03-1d501d66ccd8.png)

The mod will now sync inventory filters, fixing this issue. However, it still takes an _obscenely long time_ to sync your blueprint books, so I would either move those to the blueprint library, or just not use inventory sync at all. I will contact the developers to see if they can make any performance improvements to that logic.
