### ISSUE TITLE
editor mode deleting items from non editor mode inventory

### ISSUE THREAD

**Issue by DeadlyKitten37** [raiguard/Factorio-EditorExtensions#80]
Describe the Bug:
If you go into editor mode with extra inventory slots the mod does not account for the extra inventory slots and will delete some of your items by removing the slots they used to occupy 

To Reproduce:
open save
observe inventory, particular the last row of the inventory
open editor mode using the quick bar button
close editor mode with quick bar button
observe inventory again, the last row has been deleted 

Save file:
[z randtorio 1 expanse bug.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/7715047/z.randtorio.1.expanse.bug.zip)

**Comment by raiguard** [comment]
Unfortunately fixing this isn't really feasible. You can work around it by increasing the map editor's inventory size in the startup settings to a size that you're sure will be able to hold all of your items. You could also disable inventory sync.

**Comment by DeadlyKitten37** [comment]
I tried your proposed solution of changing the editor inventory size and found that the setting does not work

to Reproduce
load the same save as before
exit save
change the editor inventory size in the mod setting to 2000
let game reboot
load the same save as before and repeat same steps as before
observe the inventory is still not big

**Comment by raiguard** [comment]
I changed the inventory size to 2000 and tested it, and it works fine. I can't reproduce what you're talking about.

You can still reply to closed issues and I'll still see it, by the way.

**Comment by DeadlyKitten37** [comment]
i tried it and it didnt work, a couple days later and i think i found the issue, the change in map settings is only applied to new saves, if you change the setting and load an old save then the change is not applied

**Comment by raiguard** [comment]
Huh, might be a bug with the base game, I'll take a look.

**Comment by raiguard** [comment]
I took a look at this, and it indeed does not change the editor inventory size after the game has already been started. This is a bug with the base game.

**Comment by raiguard** [comment]
Bug report: https://forums.factorio.com/101181
