### ISSUE TITLE
Option to enter testing scenario in editor mode

### ISSUE THREAD

**Issue by Purpzie** [raiguard/Factorio-EditorExtensions#82]
Whenever I use that scenario (extremely often) I always immediately enable editor mode since it's easier to build with. It would be awesome if there was an option to do that automatically.

**Comment by raiguard** [comment]
Great idea!

![image](https://user-images.githubusercontent.com/3515394/148659980-4d7ac569-1848-4db6-9278-2c7be8e318ee.png)
