### ISSUE TITLE
Placing, then opening infinity pipe for config causes non-recoverable error in editor

### ISSUE THREAD

**Issue by zelmak** [raiguard/Factorio-EditorExtensions#84]
#### Describe the Bug

With only Base, Editor Extensions, and the req'd lib installed. Placing an infinity pipe and trying to configure it causes a crash out of the session with unrecoverable error.

The mod Editor Extensions (1.12.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::on_gui_opened (ID 86)
__EditorExtensions__/scripts/entity/infinity-pipe.lua:590: attempt to index field 'infinity_pipe_amount_types' (a nil value)
stack traceback:
	__EditorExtensions__/scripts/entity/infinity-pipe.lua:590: in function 'create_gui'
	__EditorExtensions__/control.lua:436: in function <__EditorExtensions__/control.lua:412>

#### To Reproduce

1. Select Single Player -> New Game 
2. Click on User Scenarios: testing (Testing)
3. Click Play
4. Scenario loads, get a bunch of migrated content (not sure where that's coming from since I have no other mods installed -- did I somehow overwrite the scenario?) and the game pauses/locks for some kind of loading thing (the radar animation stops for a second or two -- I'm guessing loading the "everything" logistic chest.)
5. Place an infinity pipe.
6. Try to open it it for config OR delete it and get an unrecoverable error.

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/7874184/factorio-current.log)
[BugReport.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/7874195/BugReport.zip)

In-game username is ClulessNoob

**Comment by zelmak** [comment]
Ah, never mind... it wasn't the right scenario. It looks like I'd saved an editor extension save as a scenario a while back and wasn't using the right starting scenario?

**Comment by raiguard** [comment]
That is super strange, I'm not sure why it wouldn't have run the migration. To fix your saves, run the following in the console before opening a pipe:
`/c __EditorExtensions__ global.infinity_pipe_amount_types = {}`
