### ISSUE TITLE
Unrecoverable error while running event EditorExtensions::on_player_setup_blueprint 

### ISSUE THREAD

**Issue by rpdelaney** [raiguard/Factorio-EditorExtensions#86]
#### Describe the Bug

When copy-pasting an infinity pipe:

```
The mod Editor Extensions (1.12.4) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::on_player_setup_blueprint (ID 69)
__EditorExtensions__/scripts/entity/infinity-pipe.lua:55: attempt to index local 'entity' (a nil value)
stack traceback:
	__EditorExtensions__/scripts/entity/infinity-pipe.lua:55: in function 'setup_blueprint'
	__EditorExtensions__/control.lua:535: in function <__EditorExtensions__/control.lua:496>
```

#### To Reproduce

Copy an infinity pipe with sulfuric acid.

#### Save file & Username

Same as #85 

#### Log file

Attach `factorio-current.log`, found in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/7916399/factorio-current.log)

**Comment by raiguard** [comment]
I fixed the crash, but this is happening because one of your other mods is deleting the infinity pipe from the blueprint for some reason. Now instead of crashing, you just can't make blueprints of infinity pipes. I tried a few of the blueprint-related mods but couldn't figure out which one it was.

**Comment by rpdelaney** [comment]
> Now instead of crashing, you just can't make blueprints of infinity pipes.

Oof. That's a Pyrrhic victory for me lol. I'll try to see if I can figure out which mod it is. I have some blueprint-adjacent mods that I don't use much.
