### ISSUE TITLE
Non Recoverable error when copying infinity pipe.

### ISSUE THREAD

**Issue by ArnthBebastien** [raiguard/Factorio-EditorExtensions#87]
Attempting to copy a section of my Krastorio 2 factory causes a non-recoverable error, this has happened a few times and every time has involved the infinity pipe.

1. Go to the bottom left corner of the lithium production area (-498,206)
2. Select the copy tool
3. use the copy tool to select an area including the infinity pipe and a sizeable chunk of the electrolysis machines
4. see error

Username: ArnthBebastien

Save File: https://www.dropbox.com/t/7qE5AjQLCJ8xvShq

I couldn't figure out how to attach the log file I've never used GitHub before im sorry.

**Comment by raiguard** [comment]
Are you on the latest version? I just fixed this a few hours ago.

**Comment by ArnthBebastien** [comment]
I was not, thank you for the fix it all seems to be working now.
Thank you for making this mod and have a nice day :)
