### ISSUE TITLE
Crash caused by switching to editor

### ISSUE THREAD

**Issue by AliquidNovi** [raiguard/Factorio-EditorExtensions#9]
There is a crash in Factorio when editor extensions is used to switch to the editor mode. Screenshot included
![2020-04-26](https://user-images.githubusercontent.com/64358106/80308056-ba783000-87c4-11ea-8761-bdf40a46a993.png)

**Comment by AliquidNovi** [comment]
Version 18.21

**Comment by raiguard** [comment]
Could you please send me the save file where this occured?

**Comment by 343N** [comment]
I'm getting the same issue, on the same version, (Editor Extensions 1.4.1, Factorio 18.21) but I have a large mod list. Still want my save?
[SANDBOX WORLD.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/4537643/SANDBOX.WORLD.zip)

**Comment by 343N** [comment]
For now, it seems disabling the mod per-player setting "Sync inventory between play modes" stops the crash.
![image](https://user-images.githubusercontent.com/10753324/80337178-9851e100-889c-11ea-86cc-544d349b4e9a.png)

**Comment by raiguard** [comment]
Thanks for providing a save! It's really helpful. :D

I fixed this for the next release.

**Comment by raiguard** [comment]
Re-opening for visibility.

**Comment by raiguard** [comment]
This got fixed forever ago but I forgot to close the issue.
