### ISSUE TITLE
Crash in test scenario

### ISSUE THREAD

**Issue by GeneralTanker** [raiguard/Factorio-EditorExtensions#90]
#### Describe the Bug

When in the test scenario opening the Infinity pipe GUI crashes the GUI 

The mod Editor Extensions (1.12.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::on_gui_opened (ID 86)
__EditorExtensions__/scripts/entity/infinity-pipe.lua:593: attempt to index field 'infinity_pipe_amount_types' (a nil value)
stack traceback:
	__EditorExtensions__/scripts/entity/infinity-pipe.lua:593: in function 'create_gui'
	__EditorExtensions__/control.lua:452: in function <__EditorExtensions__/control.lua:428>

#### To Reproduce

1. Go into test scenario
2. Place Infinity pipe
3. Click the Infinity pipe to open the GUI
4. Crash

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/8107228/factorio-current.log)

#### Save file 

[Test 112.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/8107238/Test.112.zip)

**Comment by raiguard** [comment]
Not sure how your game got into that state, it should have added the table when you updated versions. You can fix it manually by typing this:

`/c __EditorExtensions__ global.infinity_pipe_amount_types = {}`

**Comment by raiguard** [comment]
I have no idea how your save got into that state, the table should have been added during mod migrations to 1.12.0. You can fix it by typing the following:

`/c __EditorExtensions__ global.infinity_pipe_amount_types = {}`
