### ISSUE TITLE
flipped linked-belt

### ISSUE THREAD

**Issue by plaxorizor** [raiguard/Factorio-EditorExtensions#93]
The bug occurs when krastorio2 is active.

The linked-belt seems to be reversed when built

however, it was temporarily fixed when I try to remove a certain line of code in krastorio/scripts/constants.lua

`constants.transport_belt_connectable_types = {
["transport-belt"] = true,
["underground-belt"] = true,
["splitter"] = true,
["loader"] = true,
["loader-1x1"] = true,
["linked-belt"] = true, <-- this one
}`

**Comment by raiguard** [comment]
This is actually a bug in Krastorio 2. Fixed for the next version.

Ref: https://github.com/raiguard/krastorio-2/commit/591154e810fe65249d7db8cf961856cf7d60739c
